### ISSUE TITLE
Is it possible to use byebug when running tests?

### ISSUE THREAD

**Issue by gregblass** [highfidelity/fake_braintree#106]
Just want to be able to debug stuff when working on this gem / running rspec. Is this possible somehow? Doesn't seem to be as straightforward as adding it to the gemfile.

**Comment by wacii** [comment]
You could actually just add it to the gemfile, although the preferred method is to add it as a development dependency to the gemspec.

**Comment by gregblass** [comment]
I thought thats where it would go after poking around. I tried adding

    s.add_development_dependency 'byebug'

to the fake_braintree.gemspec and running 'bundle install', but I'm still getting

    NameError - undefined local variable or method `byebug'

when I run tests.

**Comment by gregblass** [comment]
Adding 'require 'byebug'' to my spec helper did the trick.

**Comment by Lewiscowles1986** [comment]
@gregblass I had to do both interestingly, which I believe is because the setup of the gem I wanted to debug via Bundler.

I'd not knowingly encountered this before, so maybe it's always been done for me; but it was surprising.

https://web.archive.org/web/20100925075146/http://gembundler.com/v1.0/rationale.html looks like rails spoiled me and anything non-rails I use has had `bundler/setup` or something similar manage the include path.
